# Dynamic Programming
---
> 동적계획법 실습
1. Policy Iteration
2. Value Iteration

- D.P 는 공통적으로 Model-based 방법이다

### 2.Value Iteration
---

* Off - Policy method
* P.I 와 다르게 평가만 한다
* Bellman Optimality Equation 사용하므로 기댓값 계산을 하지않는다.
    * 즉 value 에 매우 더 implicit 한 policy 가 들어가 있음
* 그 equation 을 iteration 하게 만들어 알고리즘을 만듬
* 대신 Greedy 알고리즘을 사용하는데, 반복하면 P.I 와 같은 Value table 값으로 수렴하게 된다.
- Value 와 Policy 를 따로 두지 않는다.
* D.P 알고리즘은 고정점 정리에 의해 수렴이 증명이 된 듯
* 모든 max 를 취하는 알고리즘의 문제 -> 과대평가

In [31]:
class Value_Iteration:
    
    def __init__(self):
        self.n_map = 4
        self.n_action = 4
        self.gamma = 0.9
        self.grid_world = np.array([0,0,0,0,
                     0,-1,0,-1,
                     0,0,0,-1,
                    -1,0,0,1]).reshape(self.n_map,-1)
        self.value = np.zeros_like(self.grid_world)
    
    
    '''
    Evaluation
    '''
    def Evaluation(self):
        v_tmp = np.zeros_like(self.grid_world, dtype=np.float16)
        for row in range(self.n_map):
            for col in range(self.n_map):
                
                max_val = -9999
                for a in range(self.n_action):
                    reward = self.get_reward(a, row, col)
                    
                    # V.I 계산식 - bellman optimality equation.
                    next_state = self.get_state(a, row, col)
                    max_tmp = reward + self.gamma * self.value[next_state[0], next_state[1]]
                    if(max_tmp > max_val):
                        max_val = max_tmp
                        
                v_tmp[row, col] = max_val
        
        v_tmp[3,3] = 0
        self.value = v_tmp
        

    '''
    R(s,a)
    P(s'|s,a)
    
    0  1  2  3
    상 하 좌 우
    '''
    def get_reward(self, a, r, c):
        
        if(a == 0 and r > 0):
            r -= 1

        elif(a == 1 and r < 3):
            r += 1

        elif(a == 2 and c > 0):
            c -= 1

        elif(a == 3 and c < 3):
            c += 1

        # 맵 넘어가면 부적 보상
        else:
            return -100

        reward = self.grid_world[r, c]

        return reward

    
    '''
    next state
    '''
    def get_state(self, a, r, c):
        
        if(a == 0 and r > 0):
            r -= 1

        elif(a == 1 and r < 3):
            r += 1

        elif(a == 2 and c > 0):
            c -= 1

        elif(a == 3 and c < 3):
            c += 1
            
        return r, c

In [32]:
v_i = Value_Iteration()

In [41]:
for i in range(10):
    v_i.Evaluation()

print(v_i.grid_world)
print(v_i.value)

[[ 0  0  0  0]
 [ 0 -1  0 -1]
 [ 0  0  0 -1]
 [-1  0  0  1]]
[[0.591  0.6562 0.729  0.6562]
 [0.6562 0.729  0.81   0.729 ]
 [0.729  0.81   0.9    1.    ]
 [0.81   0.9    1.     0.    ]]
