In [68]:
import numpy as np

In [320]:
'''
environment
'''

n_map = 4
n_action = 4
action = np.array([0,1,2,3]) # 상하좌우

# env
grid_world = np.array([0,0,0,0,
                     0,-1,0,-1,
                     0,0,0,-1,
                    -1,0,0,1]).reshape(n_map,-1)

# move 만 하는 함수
def move(a, r, c):
    if(a == 0 and r > 0):
        r -= 1
        
    elif(a == 1 and r < 3):
        r += 1
        
    elif(a == 2 and c > 0):
        c -= 1
        
    elif(a == 3 and c < 3):
        c += 1
        

# R(s,a)
# P(s'|s,a)
def get_reward(a, r, c):

    reward = 0
    
    if(a == 0 and r > 0):
        r -= 1
        
    elif(a == 1 and r < 3):
        r += 1
        
    elif(a == 2 and c > 0):
        c -= 1
        
    elif(a == 3 and c < 3):
        c += 1
        
    else:
        return reward
    
    reward = grid_world[r, c]

    return reward

        
# discount factor
gamma = 0.9

# value table
# policy table
value = np.zeros_like(grid_world)
policy = np.ones([n_action, n_map, n_map]) / n_action

In [321]:
def evaluation(value):
    next_v = np.zeros_like(grid_world, dtype=np.float16)
    
    # 모든 state 에 대해서
    for row in range(n_map):
        for col in range(n_map):
            for a in range(n_action):
                reward = get_reward(a, row, col)
                #print(reward)
                next_v[row, col] += policy[a, row, col] * (reward + gamma * value[row, col])
    
    value = next_v
    return value

In [335]:
for i in range(10):
    value = evaluation(value)
print(value)

[[ 0.    -2.492  0.    -2.492]
 [-2.492  0.    -4.984 -2.492]
 [-2.492 -2.492 -2.492  0.   ]
 [ 0.    -2.492  2.492 -2.492]]


In [101]:
def improvement():
    pass