# PyTorch
---
## pytorch 로 갈아타기
---
* define by run - 직관적임. 빠르게 작성 가능
* https://pytorch.org/docs/stable/distributions.html#score-function - policy gradient 를 위한 score function
* zero grad 해주는 것 중요
* 그래디언트 계산 후 optimizer 업데이트
* https://monkey3199.github.io/develop/python/2018/12/04/python-pararrel.html - 파이썬 멀티쓰레드 vs 멀티프로세스
* https://medium.com/@grvsinghal/speed-up-your-python-code-using-multiprocessing-on-windows-and-jupyter-or-ipython-2714b49d6fac - jupyter 에서 멀티프로세스 구동가능법
* https://github.com/MorvanZhou/pytorch-A3C/blob/master/discrete_A3C.py - 멀티프로세스 상속

In [245]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.autograd import Variable
import numpy as np

In [24]:
x = torch.Tensor(3,2)
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [32]:
x = torch.Tensor(2,3)
y = torch.Tensor(2,3)
x_ = x.add(y)
z = x.add_(y)
print(x_)
print(z)

tensor([[-1.2789e-26,  2.7655e+24,  6.3233e+17],
        [ 3.2992e-12,  1.2457e+09,  3.1844e+24]])
tensor([[-1.2789e-26,  2.7655e+24,  6.3233e+17],
        [ 3.2992e-12,  1.2457e+09,  3.1844e+24]])


In [41]:
torch.rand(3,2)
result = torch.Tensor()
torch.add(x, y, out = result)
print(result)

tensor([[-2.5577e-26,  5.5311e+24,  1.2647e+18],
        [ 6.5983e-12,  2.4915e+09,  6.3688e+24]])


In [74]:
print(x[0:2 , 0:3])
x[:,-1]

tensor([[-1.2789e-26,  2.7655e+24,  6.3233e+17],
        [ 3.2992e-12,  1.2457e+09,  3.1844e+24]])


tensor([6.3233e+17, 3.1844e+24])

In [96]:
x = torch.rand(10)
x_ = x.numpy()
print(x.view(2,-1))
print(torch.ones(5))
print(torch.from_numpy(x_))

tensor([[0.8045, 0.5471, 0.6532, 0.6881, 0.0970],
        [0.9023, 0.7274, 0.9176, 0.0089, 0.4032]])
tensor([1., 1., 1., 1., 1.])
tensor([0.8045, 0.5471, 0.6532, 0.6881, 0.0970, 0.9023, 0.7274, 0.9176, 0.0089,
        0.4032])


# Variable

In [132]:
v = Variable(torch.ones(2,4), requires_grad=True)
v_ = v + 4
z = v_.mean()
print(v_.grad_fn)
z.backward()
print(v.grad)

tensor([[0.1250, 0.1250, 0.1250, 0.1250],
        [0.1250, 0.1250, 0.1250, 0.1250]])


In [260]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(3, 5)
        self.fc2 = nn.Linear(5, 10)
        self.fc3 = nn.Linear(10, 4)
        
    def out1(self, x):
        x = self.fc1(x)
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))
        return x
    
    def out2(self, x):
        x = self.fc2(x)
        x = F.sigmoid(x)
        return x

In [262]:
net = Net()
in_ = torch.ones(3)
output = net.out1(in_)
print(output)
#list(net.parameters())

In [258]:
target = torch.ones(4)
loss_f = nn.MSELoss()
loss = loss_f(target, output)
print(loss)
loss.backward()
print(loss.grad_fn)
print(loss.grad_fn.next_functions[0][0])
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])

tensor(0.7929, grad_fn=<MeanBackward0>)


In [259]:
net.zero_grad()
optimizer = optim.Adam(net.parameters(), lr=.001)
optimizer.zero_grad()
optimizer.step()